coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 5
    
    patch:
      default:
        target: 80%
    
    changes:
      enabled: false

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
