name: Ask2God CI

on:
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  component-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: component test
      run: |
        cd ./api/
        npm install
        npm run start &
        cd ..
        npm install
        npm install -g jest-cli
        npm test
    - name: component test coverage
      run: |
        bash <(curl -s https://codecov.io/bash) -cF javascript
